name: Release Helm charts to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Chart Releaser Action
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts           # 你的 charts 目录（默认 charts）
          publish_dir: gh-pages       # 临时工作分支/目录（action 会提交 gh-pages）
          # optional: enable_signing: true